id: whisparr
name: Whisparr
description: Whisparr application.
links:
  homepage: https://whisparr.github.io/
  documentation: https://wiki.servarr.com/Whisparr
  source: https://github.com/Whisparr/Whisparr
  krate_docs: https://krate.github.io/docs/software/official/whisparr
tier: free
category: media
install_mode: local
password_constraints:
  min_length: 8
  max_length: 128
  require_upper: false
  require_digit: false
autocomplete_options:
  - -b
ui_options:
  branches:
    options:
      - main
      - beta
    label: app.branch
