id: unpackerr
name: Unpackerr
description: "Extracts archives from download clients into *arr import folders."
links:
  homepage: https://unpackerr.zip/
  documentation: https://unpackerr.zip/docs
  source: https://github.com/Unpackerr/unpackerr
  krate_docs: https://krate.github.io/docs/software/official/unpackerr
tier: free
category: download
install_mode: local
autocomplete_options:
  - -b
ui_options:
  branches:
    options:
      - main
      - beta
    label: app.branch
  subdomain:
    enabled: false
    label: app.subdomain
