id: bazarr
name: Bazarr
description: Bazarr application.
links:
  homepage: https://bazarr.media/
  documentation: https://wiki.bazarr.media/
  source: https://github.com/morpheus65535/bazarr
  krate_docs: https://krate.github.io/docs/software/official/bazarr
tier: pro
category: media
install_mode: local
password_constraints:
  min_length: 8
  max_length: 128
  require_upper: false
  require_digit: false
autocomplete_options:
  - -b
ui_options:
  branches:
    options:
      - main
      - beta
    label: app.branch
